=== aws-amplify/amplify-cli/packages/amplify-category-storage/resources/schemas/S3/S3UserInputs.schema.json
{
    "type": "object",
    "properties": {
        "resourceName": {
            "type": "string"
        },
        "bucketName": {
            "type": "string"
        },
        "policyUUID": {
            "type": "string"
        },
        "storageAccess": {
            "enum": [
                "auth",
                "authAndGuest"
            ],
            "type": "string"
        },
        "guestAccess": {
            "type": "array",
            "items": {
                "enum": [
                    "CREATE_AND_UPDATE",
                    "DELETE",
                    "READ"
                ],
                "type": "string"
            }
        },
        "authAccess": {
            "type": "array",
            "items": {
                "enum": [
                    "CREATE_AND_UPDATE",
                    "DELETE",
                    "READ"
                ],
                "type": "string"
            }
        },
        "triggerFunction": {
            "type": "string"
        },
        "groupAccess": {
            "$ref": "#/definitions/GroupAccessType"
        }
    },
    "required": [
        "authAccess",
        "bucketName",
        "guestAccess",
        "policyUUID",
        "resourceName",
        "storageAccess"
    ],
    "definitions": {
        "GroupAccessType": {
            "type": "object"
        }
    },
    "$schema": "http://json-schema.org/draft-07/schema#"
}

=== aws-amplify/amplify-cli/amplify-migration-apps/project-boards/_snapshot.pre.generate/amplify/#current-cloud-backend/storage/s369f8ff1c/cli-inputs.json
{
  "resourceName": "s369f8ff1c",
  "policyUUID": "69f8ff1c",
  "bucketName": "projectboards34b9a7f3c2ca489293910116c994688b",
  "storageAccess": "authAndGuest",
  "guestAccess": [
    "READ"
  ],
  "authAccess": [
    "CREATE_AND_UPDATE",
    "READ",
    "DELETE"
  ],
  "triggerFunction": "NONE",
  "groupAccess": {}
}
